name: Frontend CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Ubuntu latest works fine for Docker builds

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Build frontend Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ask-pdf-frontend:latest .

      - name: Push frontend image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ask-pdf-frontend:latest

      - name: Cleanup old Docker images (Optional)
        run: docker system prune -af
